<a href="https://colab.research.google.com/github/ncbrubaker/github-slideshow/blob/master/Test_Results_Nolan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Bombus affinis vs Bombus bifarius ##


tf.Tensor(
[[682  58]
 [165 575]], shape=(2, 2), dtype=int32)
              
              precision    recall  f1-score   support

         0.0       0.81      0.92      0.86       740
         1.0       0.91      0.78      0.84       740

    accuracy                           0.85      1480
   macro avg       0.86      0.85      0.85      1480
weighted avg       0.86      0.85      0.85      1480

time_saved : 1643279043.3600538

## Bombus affinis vs Bombus bimaculatus ##

tf.Tensor(
[[228 512]
 [218 522]], shape=(2, 2), dtype=int32)
              
              precision    recall  f1-score   support

         0.0       0.51      0.31      0.38       740
         1.0       0.50      0.71      0.59       740

    accuracy                           0.51      1480
   macro avg       0.51      0.51      0.49      1480
weighted avg       0.51      0.51      0.49      1480

time_saved : 1643363688.8370047


## Bombus affinis vs Bombus borealis ##

tf.Tensor(
[[636 104]
 [202 538]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.76      0.86      0.81       740
         1.0       0.84      0.73      0.78       740

    accuracy                           0.79      1480
   macro avg       0.80      0.79      0.79      1480
weighted avg       0.80      0.79      0.79      1480

time_saved : 1643454003.076377

## Bombus affinis vs Bombus citrinus ##

tf.Tensor(
[[230 346]
 [179 397]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.56      0.40      0.47       576
         1.0       0.53      0.69      0.60       576

    accuracy                           0.54      1152
   macro avg       0.55      0.54      0.53      1152
weighted avg       0.55      0.54      0.53      1152

time_saved : 1643438637.679892

## Bombus affinis vs Bombus centralis ##

tf.Tensor(
[[660  40]
 [159 541]], shape=(2, 2), dtype=int32)
              
              precision    recall  f1-score   support

         0.0       0.81      0.94      0.87       700
         1.0       0.93      0.77      0.84       700

    accuracy                           0.86      1400
   macro avg       0.87      0.86      0.86      1400
weighted avg       0.87      0.86      0.86      1400

time_saved : 1643395479.7903736


## Bombus affinis vs Bombus fernaldae flavidus ##

tf.Tensor(
[[320  96]
 [129 287]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.71      0.77      0.74       416
         1.0       0.75      0.69      0.72       416

    accuracy                           0.73       832
   macro avg       0.73      0.73      0.73       832
weighted avg       0.73      0.73      0.73       832

time_saved : 1643412979.7458477

## Bombus affinis vs Bombus flavifrons ##

tf.Tensor(
[[656  84]
 [227 513]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.74      0.89      0.81       740
         1.0       0.86      0.69      0.77       740

    accuracy                           0.79      1480
   macro avg       0.80      0.79      0.79      1480
weighted avg       0.80      0.79      0.79      1480

time_saved : 1643414136.7685068

## Bombus affinis vs Bombus fervidus californicus ##

tf.Tensor(
[[596 144]
 [295 445]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.67      0.81      0.73       740
         1.0       0.76      0.60      0.67       740

    accuracy                           0.70      1480
   macro avg       0.71      0.70      0.70      1480
weighted avg       0.71      0.70      0.70      1480

time_saved : 1643465463.099939

## Bombus affinis vs Bombus griseocollis ##

tf.Tensor(
[[170 570]
 [179 561]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.49      0.23      0.31       740
         1.0       0.50      0.76      0.60       740

    accuracy                           0.49      1480
   macro avg       0.49      0.49      0.46      1480
weighted avg       0.49      0.49      0.46      1480

time_saved : 1643465576.4054132

## Bombus affinis vs Bombus impatiens ##

tf.Tensor(
[[156 584]
 [144 596]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.52      0.21      0.30       740
         1.0       0.51      0.81      0.62       740

    accuracy                           0.51      1480
   macro avg       0.51      0.51      0.46      1480
weighted avg       0.51      0.51      0.46      1480

time_saved : 1643424974.8233218

## Bombus affinis vs Bombus insularis ##

tf.Tensor(
[[402  92]
 [217 277]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.65      0.81      0.72       494
         1.0       0.75      0.56      0.64       494

    accuracy                           0.69       988
   macro avg       0.70      0.69      0.68       988
weighted avg       0.70      0.69      0.68       988

time_saved : 1643438508.018142

## Bombus affinis vs Bombus melanopygus ##

tf.Tensor(
[[664  76]
 [217 523]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.75      0.90      0.82       740
         1.0       0.87      0.71      0.78       740

    accuracy                           0.80      1480
   macro avg       0.81      0.80      0.80      1480
weighted avg       0.81      0.80      0.80      1480

time_saved : 1643521338.5460365

## Bombus affinis vs Bombus mixtus ##

tf.Tensor(
[[688  52]
 [146 594]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.82      0.93      0.87       740
         1.0       0.92      0.80      0.86       740

    accuracy                           0.87      1480
   macro avg       0.87      0.87      0.87      1480
weighted avg       0.87      0.87      0.87      1480

time_saved : 1643526580.34485

## Bombus affinis vs Bombus nevadensis ##

tf.Tensor(
[[616 124]
 [164 576]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.79      0.83      0.81       740
         1.0       0.82      0.78      0.80       740

    accuracy                           0.81      1480
   macro avg       0.81      0.81      0.81      1480
weighted avg       0.81      0.81      0.81      1480

time_saved : 1643550113.8700035

## Bombus affinis vs Bombus pensylvanicus sonorus ##

## Bombus affinis vs Bombus perplexus ##

tf.Tensor(
[[228 512]
 [201 539]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.53      0.31      0.39       740
         1.0       0.51      0.73      0.60       740

    accuracy                           0.52      1480
   macro avg       0.52      0.52      0.50      1480
weighted avg       0.52      0.52      0.50      1480

time_saved : 1643579463.9641628

## Bombus affinis vs Bombus rufocinctus ##

tf.Tensor(
[[538 202]
 [321 419]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.63      0.73      0.67       740
         1.0       0.67      0.57      0.62       740

    accuracy                           0.65      1480
   macro avg       0.65      0.65      0.64      1480
weighted avg       0.65      0.65      0.64      1480

time_saved : 1643614847.4801285

## Bombus affinis vs Bombus huntii ##

tf.Tensor(
[[686  54]
 [208 532]], shape=(2, 2), dtype=int32)
 
              precision    recall  f1-score   support

         0.0       0.77      0.93      0.84       740
         1.0       0.91      0.72      0.80       740

    accuracy                           0.82      1480
   macro avg       0.84      0.82      0.82      1480
weighted avg       0.84      0.82      0.82      1480

time_saved : 1643646830.9093943

## Bombus affinis vs Bombus ternarius ##

## Bombus affinis vs Bombus terricola ##

## Bombus affinis vs Bombus vagans ##